# Generated by Django 4.2.7 on 2023-12-28 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_chat_message_chat_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='chat_id',
        ),
    ]
